Improve user output
privML/privacy-evaluator pull request #122
Opened 2021-06-06 12:55 UTC by Erdnaf

Implementation of the improved User Outputs with relative plots and other small changes.

closes #118

2021-06-08 07:03 UTC, budmil approved these changes

2021-06-10 11:17 UTC, marisanest requested changes

2021-06-10 11:17 UTC, marisanest commented on tests/output/output_test.py
> +    )
Nice testing here :+1:

2021-06-10 11:17 UTC, marisanest commented on privacy_evaluator/output/user_output.py
> +        label_counts: np.ndarray,
Maybe calculate these values within the method instead of having a parameter here. But the rest looks fine :100:

2021-06-10 15:16 UTC, marisanest approved these changes
Looks good, I will merge it now.

2021-06-10 15:19 UTC, merged