restructure priv risk score to be mia on point basis #151
privML/privacy-evaluator pull request #180
Opened 2021-06-25 13:59 UTC by blauertee

Wasn't able to test thoroughly again because of cuda errors, so please run the code :)

2021-06-27 16:37 UTC, marisanest requested changes
Nice implementation :100: I fixed black formatting and a little bug. Please also check the notebooks. I think you also need to change them as well.

2021-06-27 16:37 UTC, marisanest commented on privacy_evaluator/attacks/membership_inference/on_point_basis.py
> +    def _compute_membership_probability(
You could have left this functin in the metrics module. But its only used here so it's fine.

2021-06-28 10:27 UTC, budmil approved these changes

2021-06-30 06:09 UTC, Erdnaf commented
hey, I tried to run the new notebook, but when running it on my PC my pc stragely hangs on the cell where the attack is performed and frezzes 😢 . When running it on colab I get an Cuda error. Are you shure that it runs for you? Also in the notebook?
@blauertee @marisanest @jtorhoff

2021-06-30 08:27 UTC, jtorhoff commented
I think we have a little problem here:

<img width="346" src="https://user-images.githubusercontent.com/20026551/123927108-cfce8880-d98c-11eb-95f9-af7817a10fcb.png">

The process RAM usage keeps exploding. Maybe we should wait with this PR for now any then try to get to the root of the problem, but it surely is unexpected.

2021-06-30 08:34 UTC, jtorhoff commented
Btw it looks like it behaved the same way before, it's just that we didn't calculate the score for the whole dataset but only first 100 data points. Just tried it out as it was before this PR and the same problem with RAM usage occurs.

2021-06-30 10:49 UTC, merged