Integrate Sprint 6 of Team 1
privML/privacy-evaluator pull request #234
Opened 2021-07-26 13:12 UTC by Erdnaf

This is the pull request for the work of Team `#1` in Sprint `#6`.

2021-08-02 14:03 UTC, fraboeni requested changes
Hey Team 1, very good job on this sprint. After having addressed my concerns, feel free to merge your changes into the master and clean up the branch! Thank you for all the good work you have done in the project so far.

2021-08-02 14:03 UTC, fraboeni commented on privacy_evaluator/output/user_output_privacy_score.py
> +    [1] Song, Liwei and Prateek Mittal. “Systematic Evaluation of Privacy Risks of Machine Learning Models.” ArXiv
again, inside a -.py class, I would rather see links to the papers than that reference style.

2021-08-03 15:02 UTC, Friedrich-Mueller commented on privacy_evaluator/attacks/membership_inference/black_box.py
> +        :param y_train: True, one-hot encoded labels for `x_train`.
Thank you for finding that again. You addressed that in the past already and we took care of here (see here https://github.com/privML/privacy-evaluator/pull/189/commits/b5e2e9798e977036f0719785cabc9528d8f537c2). I'm not sure how those got back in tbh.

2021-08-03 15:45 UTC, Friedrich-Mueller commented
I removed the 'True's again.
I am working on the references in .py-files and will correct them ASAP. Same goes for the "lowest possible accuracy" which I will update ASAP as well.

This leaves only the feedback regarding the Attacker's Advantage Score description/equation in README.

2021-08-03 18:36 UTC, Friedrich-Mueller commented
All of Franziska's comments are addressed now, but still need some peer review.

Especially the one regarding the advantage score equation.

2021-08-03 18:37 UTC, Friedrich-Mueller commented on README.md
> +The metric represents the attacker's advantage score.  It represents the degree to which a learning algorithm, i.e. a model, reveals membership to an adversary. The score calculation is based on Defi
I added a simple equation. I'm not sure if its fine like that or if it needs further denotions or explanations.

2021-08-04 11:12 UTC, marisanest commented
Thanks @Friedrich-Mueller! I checked everything and it all looks quite good to me. Just added some really small additional explanations to the equation.

2021-08-16 14:42 UTC, merged